services:
    # API Backend Service
    api:
        build:
            context: ./api
            dockerfile: Dockerfile

        ports:
            - "0.0.0.0:8000:8000"

        env_file:
            - ./api/.env

        volumes:
            - ./api:/api

        # Use host.docker.internal to access host services like Ollama
        extra_hosts:
            - "host.docker.internal:host-gateway"

        restart: unless-stopped

    # Web App Service
    webapp:
        build:
            context: ./app
            dockerfile: Dockerfile

        ports:
            - "0.0.0.0:80:80"

        env_file:
            - ./app/.env

        restart: unless-stopped

    # Full Stack (launches both services)
    full:
        image: hello-world

        depends_on:
            - api
            - webapp

        profiles: ["full"]

volumes:
    api-data:
    api-logs:
