# EchoTuner Docker Compose Configuration
# This configuration uses pre-built images from Github Container Registry (GHCR).
# To use local builds instead, use docker compose up --build.

services:
  # API Backend Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    image: ghcr.io/domasles/echotuner/echotuner-api:latest
    container_name: api

    ports:
      - "0.0.0.0:8000:8000"

    env_file:
      - ./api/.env

    volumes:
      - ./api/storage:/api/storage

    # Use host.docker.internal to access host services like Ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

  # Web App Service
  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile

    image: ghcr.io/domasles/echotuner/echotuner-webapp:latest
    container_name: webapp

    ports:
      - "0.0.0.0:80:80"

    env_file:
      - ./app/.env

    restart: unless-stopped

  # Full Stack (launches both services)
  full:
    image: hello-world

    depends_on:
      - api
      - webapp

    profiles: ["full"]
