name: echotuner
description: AI-powered Spotify playlist generator

publish_to: 'none'
version: 1.1.0+2

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    http: ^1.4.0
    provider: ^6.1.2

    shared_preferences: ^2.5.3
    device_info_plus: ^11.5.0
    
    url_launcher: ^6.2.1
    json_annotation: ^4.8.1
    flutter_dotenv: ^5.1.0

    flutter_svg: ^2.0.9
    cupertino_icons: ^1.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    
    flutter_lints: ^6.0.0
    json_serializable: ^6.9.5
    build_runner: ^2.4.7

flutter:
    uses-material-design: true
    
    assets:
        - .env
