name: echotuner
description: AI-powered Spotify playlist generator

publish_to: 'none'
version: 1.7.0-beta+1

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    provider: ^6.1.5
    http: ^1.4.0

    shared_preferences: ^2.5.3
    device_info_plus: ^11.5.0

    json_annotation: ^4.9.0
    flutter_dotenv: ^5.2.1
    universal_html: ^2.2.4
    url_launcher: ^6.3.1

    cupertino_icons: ^1.0.8
    flutter_svg: ^2.2.0

    responsive_framework: ^1.5.1
    flutter_screenutil: ^5.9.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: ^0.14.4
    json_serializable: ^6.9.5
    flutter_lints: ^6.0.0
    build_runner: ^2.5.4

flutter:
    uses-material-design: true

    assets:
        # Uncomment the following line if you want to build locally
        - .env

        - assets/logos/EchoTunerLogo.svg
        - assets/logos/SpotifyLogo.svg

        - assets/icons/EchoTunerIcon.png

flutter_launcher_icons:
    android: true
    ios: true
    remove_alpha_ios: true

    windows:
        generate: true
        image_path: "assets/icons/EchoTunerIcon.png"
        icon_size: 256

    macos:
        generate: true
        image_path: "assets/icons/EchoTunerIcon.png"

    web:
        generate: true
        image_path: "assets/icons/EchoTunerIcon.png"

    image_path: "assets/icons/EchoTunerIcon.png"

    adaptive_icon_background: "#000000"
    adaptive_icon_foreground: "assets/icons/EchoTunerIcon.png"
