"""
Application constants for EchoTuner API.
Centralized constants for app name, version, colors, and other static values.
"""

class AppConstants:
    """Centralized application constants."""

    API_NAME = "EchoTuner"
    API_TITLE = "EchoTuner API"
    API_VERSION = "1.7.2-beta"

    DATABASE_FILEPATH = "storage/echotuner.db"
    SPOTIFY_TOKEN_CACHE_FILEPATH = "storage/spotify_token_cache.json"

    REQUIRED_DIRECTORIES = ["storage"]

    DEFAULT_PLAYLIST_DESCRIPTION = "Generated by EchoTuner AI"
    API_WELCOME_MESSAGE = "EchoTuner API"
    STARTUP_MESSAGE = "EchoTuner API - AI-Powered Playlist Generation"

    LOGGER_COLORS = {
        'DEBUG': 'cyan',
        'INFO': 'green',
        'WARNING': 'yellow',
        'ERROR': 'red',
        'CRITICAL': 'bright_red',
        API_NAME: 'magenta'
    }

    # Year ranges for music search
    RECENT_YEARS = ["2020", "2021", "2022", "2023", "2024"]
    POPULAR_YEARS = ["2018", "2019", "2020", "2021", "2022", "2023", "2024"]
    DISCOVERY_YEARS = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024"]

app_constants = AppConstants()
