# The Site Configuration

theme: jekyll-theme-chirpy
lang: en
timezone: Europe/Vilnius
title: EchoTuner Documentation
tagline: AI-powered Spotify playlist generator

description: >-
  Comprehensive documentation for EchoTuner, an AI-powered Spotify playlist generator.
  It creates personalized playlists based on your mood, preferences, and listening history.

url: "https://echotuner-docs.domax.lt"

github:
  username: domasles

twitter:
  username:

social:
  name: Domas Leščinskas
  email: domas.lescinskas@gmail.com
  links:
    - https://github.com/domasles

webmaster_verifications:
  google:
  bing:
  alexa:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode:
cdn:
avatar: "/assets/img/logo.svg"
social_preview_image:
toc: true

comments:
  provider: disqus
  disqus:
    shortname: EchoTuner
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled: false
    env: # [development | production]

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10
baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
